camunda/camunda-bpmn-js

- .npmignore
- CHANGELOG.md
- README.md
- docs/DISTRIBUTIONS.md
Closes #1
Related to https://github.com/zeebe-io/zeebe-modeler/issues/288
> Add Getting Started and Distributions docs

- lib/camunda-cloud/Modeler.js
- lib/camunda-cloud/features/disable-user-tasks/DisableUserTasks.js
- lib/camunda-cloud/features/disable-user-tasks/index.js
- test/camunda-cloud/features/disable-user-tasks/DisableUserTasksSpec.js
- test/camunda-cloud/features/palette/PaletteProviderSpec.js
I decided to solve it via a small extension which disables all part of the user tasks support (replace menu, properties provider, modeling behaviors) to keep the basic modules untouched. Once we achieve support with the May release, we can simply remove this extension.
Note: it can be re-enabled once configured via `enableZeebeUserTasks` flag.
Related to camunda/camunda-modeler#2140
> feat(camunda-cloud): disable user task support

- .github/dependabot.yml
I thought about adding other dependencies as well, as `bpmn-js-properties-panel` or `camunda-bpmn-moddle` where we had multiple (manual) updates in the past. 
However, it's not supported currently to group these updates into a single PR (https://github.com/dependabot/dependabot-core/issues/1190). Also, the amount of libraries we have to update after a `bpmn-js-properties-panel` or `camunda-bpmn-moddle` release is not as high as for `bpmn-js`, so it's okay for now.
> chore: add dependabot config to bump on bpmn-js updates

- lib/camunda-platform/features/modeling/behavior/DeleteErrorEventDefinitionBehavior.js
- lib/camunda-platform/features/modeling/behavior/UpdateResultVariableBehavior.js
- lib/camunda-platform/features/modeling/behavior/index.js
- test/camunda-platform/features/modeling/DeleteErrorEventDefinitionBehaviorSpec.js
- test/camunda-platform/features/modeling/UpdateResultVariableBehaviorSpec.js
- test/camunda-platform/features/modeling/camunda-error-event-definition-diagram.bpmn
- test/camunda-platform/features/modeling/camunda-result-variable-diagram.bpmn
Related to bpmn-io/bpmn-properties-panel#41
Ensures we
* clean up error event definitions once service task type got changed to something different then `external`
* clean up `camunda:mapDecisionResult` for empty result variables
> Platform implementation behaviors

- lib/camunda-platform/features/modeling/behavior/UserTaskFormsBehavior.js
- lib/camunda-platform/features/modeling/behavior/index.js
- package-lock.json
- package.json
- test/camunda-platform/features/modeling/UserTaskFormBehaviorSpec.js
- test/camunda-platform/features/modeling/camunda-user-task-forms-diagram.bpmn
* setting `camunda:formKey` deletes `camunda:formRef`, `camunda:formRefBinding` and `camunda:formRefVersion`
* setting `camunda:formRef` deletes `camunda:formKey`
* deleting `camunda:formRef` deletes `camunda:formRefBinding` and `camunda:formRefVersion`
* setting `camunda:formRefBinding` to something other than `version` deletes `camunda:formRefVersion`
Depends on ttps://github.com/camunda/camunda-bpmn-moddle/pull/76
Closes #37
Related to https://github.com/camunda/camunda-modeler/issues/2295
> feat(camunda-platform): set either camunda:formKey or formRef

- lib/camunda-platform/features/modeling/behavior/UpdateInputOutputBehavior.js
- lib/camunda-platform/features/modeling/behavior/index.js
- test/camunda-platform/features/modeling/UpdateInputOutputBehaviorSpec.js
- test/camunda-platform/features/modeling/camunda-input-output-diagram.bpmn
Ensures we clean up empty `camunda:inputOutput` elements.
Related to https://github.com/bpmn-io/bpmn-properties-panel/issues/54
> feat(camunda-platform): add input output behavior

- lib/camunda-cloud/features/popup-menu/ReplaceOptions.js
- test/camunda-cloud/features/popup-menu/ReplaceMenuProviderSpec.js
- test/fixtures/diagram.bpmn
Related to https://github.com/camunda/camunda-modeler/issues/2420
Also adds tests related to replacing tasks with ManualTask, missing in https://github.com/camunda/camunda-bpmn-js/pull/49
> feat(camunda-cloud): allow replace Message Intermediate Throw and Message End events 

- lib/camunda-cloud/features/properties-provider/parts/HeadersProps.js
- lib/camunda-cloud/features/properties-provider/parts/MessageProps.js
- lib/camunda-cloud/features/properties-provider/parts/TaskDefinitionProps.js
- lib/camunda-cloud/helper/InputOutputHelper.js
- lib/camunda-cloud/helper/ZeebeServiceTaskHelper.js
- package-lock.json
- package.json
- test/camunda-cloud/features/properties-provider/PropertiesProvider.bpmn
- test/camunda-cloud/features/properties-provider/PropertiesProviderSpec.js
- Bump `zeebe-bpmn-moddle` to v0.8.0
- Remove message properties for Message End Event and Message Throw Event
- Add ZeebeServiceTask properties for  Message End Event and Message Throw Event
__Screenshot__
Normal end event:
Message end event:
> Update properties panel for Message End Event and Message Throw Event

- lib/camunda-platform/features/modeling/behavior/UserTaskFormsBehavior.js
- package-lock.json
- package.json
- test/camunda-platform/features/modeling/UserTaskFormBehaviorSpec.js
As a follow up to https://github.com/camunda/camunda-bpmn-moddle/pull/87 this ensures the resulting XML is always a valid, executable diagram.
Related to camunda/camunda-modeler#2484
> Set `camunda:formRefBinding` to latest if `camunda:formRef` is being set

- lib/camunda-platform/features/modeling/behavior/UpdateInputOutputBehavior.js
Let's use relative paths here. Some bundlers will have problems otherwise.
I stumbled over this while linking the current `main` branch to the Camunda Modeler.
```error
ERROR in /Users/niklas.kiefer/bpmn-io/camunda-bpmn-js/lib/camunda-platform/features/modeling/behavior/UpdateInputOutputBehavior.js
Module not found: Error: Can't resolve 'lib/camunda-platform/helper/InputOutputHelper' in '/Users/niklas.kiefer/bpmn-io/camunda-bpmn-js/lib/camunda-platform/features/modeling/behavior'
@ /Users/niklas.kiefer/bpmn-io/camunda-bpmn-js/lib/camunda-platform/features/modeling/behavior/UpdateInputOutputBehavior.js 2:0-99 22:26-40 29:25-43
@ /Users/niklas.kiefer/bpmn-io/camunda-bpmn-js/lib/camunda-platform/features/modeling/behavior/index.js
@ …
```
> fix(camunda-platform): use relative path in library code

- CHANGELOG.md
- lib/camunda-cloud/ElementTemplatesValidator.js
- lib/camunda-cloud/Modeler.js
- package-lock.json
- package.json
- styles/camunda-cloud-modeler.css
- test/camunda-cloud/ElementTemplatesValidatorSpec.js
- test/camunda-cloud/ModelerSpec.js
* Bumping properties panel dependencies
* Add `cloud-element-templates` provider available in Camunda Cloud Modeler
* Re-export cloud element templates validator to make it available in Camunda Modeler
* Prepare next alpha release
Related to https://github.com/camunda/camunda-modeler/issues/2731
> Rollout cloud templates

- package-lock.json
- package.json
- test/camunda-cloud/features/modeling/UpdatePropagateAllChildVariablesBehaviorIntegrationSpec.js
This is to make sure only one instance of the libraries
is installed even if the project contains extension
and imports `@bpmn-io/properties-panel/preact` or any
of the hooks.
Problem:
When I install both `camunda-bpmn-js` and `bpmn-js-properties-panel` in my project, I may end up with the following structure:
```
├── bpmn-js-properties-panel
├── camunda-bpmn-js
│   ├── node_modules
│   │   ├── bpmn-js-properties-panel
```
As a result, my `useService` import may use different context than the one used in `camunda-bpmn-js` which causes an error.
When we set the peer dependency, `bpmn-js-properties-panel` will be installed only if it's not already present in the project.
> fix: move properties panel deps to peer dependencies

- package-lock.json
- package.json
- test/base/ModelerSpec.js
- test/camunda-cloud/ModelerSpec.js
- test/camunda-platform/ModelerSpec.js
This makes the FEEL indicator available (including styles) for camunda-bpmn-js consumers:
> deps: bump to bpmn-js-properties-panel@1.0.0-alpha.7

- lib/camunda-cloud/features/modeling/behavior/CreateZeebeCallActivityBehavior.js
- test/camunda-cloud/features/modeling/CreateZeebeCallActivityBehaviorSpec.js
`$parent` wasn't being set when creating `zeebe:CalledElement`.
> fix: set $parent when creating zeebe:CalledElement element

- CHANGELOG.md
- package-lock.json
- package.json
* `FIX`: set $parent when creating zeebe:CalledElement element ([#99](https://github.com/camunda/camunda-bpmn-js/pull/99))
* `DEPS`: update to `@bpmn-io/properties-panel@0.13.1`
* `DEPS`: update to `bpmn-js-properties-panel@1.0.0-alpha.9`
* `FEAT`: allow showing entries and errors through events ([#137](https://github.com/bpmn-io/properties-panel/pull/137))
* `FEAT`: allow opening groups per default ([#139](https://github.com/bpmn-io/properties-panel/pull/139))
* `FEAT`: add documentation ref ([#141](https://github.com/bpmn-io/properties-panel/pull/141))
* `FEAT`: add show callbacks to show entries and errors ([#601](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/601))
* `FEAT`: open element template custom groups ([#621](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/6 …
> chore(CHANGELOG): update to v0.13.0-alpha.6

- CHANGELOG.md
> chore: prepare 0.13.0-alpha.8 release

- package-lock.json
- package.json
- test/camunda-cloud/ModelerSpec.js
- test/camunda-cloud/ModelerSpec.simple.bpmn
- test/camunda-cloud/element-templates.json
* include element templates
* include element template chooser
----
Spinning up the cloud modeler via `npm run start:cloud` now gives us a tool to try out C8 element templates / connectors end-to-end.
> test: make cloud-modeler demo fully functional

- package.json
`camunda-bpmn-js` and `bpmn-js-properties-panel` both have a peer dependency to `@bpmn-io/properties-panel`, so they need to match. For more context, see https://github.com/bpmn-io/internal-docs/issues/599
Closes #145
> fix: update @bpmn-io/properties-panel peer dependency to match

- package.json
* @bpmn-io/properties-panel is transitive peer dependency as it is peer dependency of bpmn-js-properties-panel
---
Related to https://github.com/bpmn-io/internal-docs/issues/599
> fix: remove @bpmn-io/properties-panel peer dependency

- CHANGELOG.md
* `FIX`: remove `@bpmn-io/properties-panel` peer dependency as it is transitive ([#147](https://github.com/camunda/camunda-bpmn-js/pull/147))
> chore(CHANGELOG): update to v0.15.3

- lib/camunda-cloud/Modeler.js
- package-lock.json
- package.json
- test/camunda-cloud/features/popup-menu/ReplaceMenuIntegrationSpec.js
related to https://github.com/bpmn-io/bpmn-js/issues/1688
What changed:
- update bpmn-js-disable-collapsed-subprocess so tasks can be morphed
- change init order of `popupMenuModule` and `disableCollapsedSubprocessModule`, so `popupMenuModule` does not override the entry created by `disableCollapsedSubprocessModule`
- add integration tests for replace menu entries
> fix(cloud): allow expanding subprocesses

- CHANGELOG.md
- package-lock.json
- package.json
This adds the FEEL editor to the Properties panel. Event though it is a peer dependency, it is required for updated style sheets in the downstream projects.
try it out with `npm run start:cloud`
> deps: bump property panel dependencies

- CHANGELOG.md
- package-lock.json
- package.json
we actually need to release a patch release on this one as we pack the properties panel CSS files into our modeler bundles
https://github.com/camunda/camunda-bpmn-js/blob/main/styles/base-modeler.css#L5
> deps: update to @bpmn-io/properties-panel@0.20.1

- package-lock.json
- package.json
We want to ensure people are using at least `v1.7.0`.
> deps: update bpmn-js-properties-panel peer dependency

- CHANGELOG.md
* `FEAT`: add inclusive gateway replacement option ([#162](https://github.com/camunda/camunda-bpmn-js/pull/162))
* `DEPS`: update to `bpmn-js-properties-panel@1.7.0`
* `FEAT`: show conditions group if source is inclusive gateway ([#756](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/756))
* `FEAT`: support element template properties without default value ([#763](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/763))
* `FEAT`: support deprecated element templates ([#766](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/766))
* `FIX`: support `zeebe:property` binding for creation of elements from element templates ([#762](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/762))
* `FIX`: support conditional properties for creation of elements from element …
> chore(CHANGELOG): update to v0.18.0

- .github/workflows/CI.yml
- CHANGELOG.md
* `FEAT`: cloud modeler allows modeling of all elements ([#196](https://github.com/camunda/camunda-bpmn-js/pull/196))
* `DEPS`: update to `diagram-js@10`
* cloud modeler allows modeling of elements not supported by the engine; use [`@camunda/linting`](https://github.com/camunda/linting) to indicate elements supported by engine
> chore(CHANGELOG): update to v0.22.0

- .github/workflows/CI.yml
This was broken with commit bc39e6bc224be61e730edb4ca63019698cdcedbe, where we only changed the os but not all references to it
> ci: run with coverage

- lib/camunda-cloud/features/replace/ElementTemplatesReplaceProvider.js
- test/camunda-cloud/ElementTemplatesReplaceProviderSpec.js
- test/camunda-cloud/ModelerSpec.js
Related to https://github.com/camunda/camunda-bpmn-js/issues/211#issuecomment-1337263134
> Hide "replace with templates" behind feature flag 

- CHANGELOG.md
- package-lock.json
- package.json
Adds touch support to the minimap (cf. https://github.com/bpmn-io/diagram-js-minimap/pull/54).
> deps: update diagram-js-minimap to v4.0.1

- .github/workflows/CI.yml
- CHANGELOG.md
- README.md
- docs/DISTRIBUTIONS.md
- package-lock.json
- package.json
Shows how automatic formatting of markdown can be achieved + introduces a `format` task to perform all formatting steps.
Markdown formatting is powered by `remark` and a [dedicated preset](https://github.com/bpmn-io/remark-preset-bpmn-io) that we can customize to suite our needs.
> Add format task + automatically format markdown

- CHANGELOG.md
- lib/camunda-platform/Modeler.js
Adds the create/append menus back to the platform modeler (without the element templates) -> current behaviour in desktop modeler that was broken when we migrated to using the `bpmn-js-create-append-anything` extension
> fix(platform): add create/append menus

- CHANGELOG.md
- package-lock.json
- package.json
* update @bpmn-io/element-template-icon-renderer to v0.5.1
* update CHANGELOG
---
Related to https://github.com/camunda/web-modeler/issues/4879
> Prepare 2.6.1 Release

- lib/camunda-cloud/Modeler.js
- lib/camunda-platform/Modeler.js
- package-lock.json
- package.json
- rollup.config.js
- test/camunda-cloud/ModelerSpec.js
- test/camunda-platform/ModelerSpec.js
related to https://github.com/camunda/camunda-modeler/issues/3357
element templates will be removed from the properties panel with https://github.com/bpmn-io/bpmn-js-properties-panel/pull/937
> chore: use element template lib

- CHANGELOG.md
- package-lock.json
- package.json
Would be cool to get this into the 5.18 release
> deps: update to `bpmn-js-element-templates@1.9.2`

- CHANGELOG.md
- package-lock.json
- package.json
Integrates https://github.com/bpmn-io/bpmn-js/pull/2069. I also had to fix the CHANGELOG after the [v3.12.0 changes were added to v3.11.0 by accident](https://github.com/camunda/camunda-bpmn-js/commit/921d784604a238f07abde0160d6eca1e4597590b).
> Update bpmn-js to v16.3.1

- CHANGELOG.md
- package-lock.json
- package.json
Let's release a patch that includes the 2 small (but impactful) fixes so web modeler can eagerly integrate them.
Desktop modeler will ship them with the next monthly release
> deps: update to bpmn-js-element-templates@1.13.2

- CHANGELOG.md
- package-lock.json
- package.json
* `FEAT`: add `Binding` entry to busines rule task, call activity and user task ([bpmn-io/bpmn-js-properties-panel#1067](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1067))
* `DEPS`: update to `@bpmn-io/properties-panel@3.22.4`
* `DEPS`: update to `bpmn-js-properties-panel@5.20.0`
* `DEPS`: update to `camunda-bpmn-js-behaviors@1.5.0`
* `DEPS`: update to `zeebe-bpmn-moddle@1.4.0`
Run `npm start` to test.
Related to https://github.com/camunda/product-hub/issues/1920
> Prepare v4.16.0

- CHANGELOG.md
- package-lock.json
- package.json
* `DEPS`: update to `@bpmn-io/properties-panel@3.26.0`
* `DEPS`: update to `@bpmn-io/variable-resolver@1.3.3`
* `DEPS`: update to `bpmn-js@18.2.0`
* `DEPS`: update to `bpmn-js-create-append-anything@0.6.0`
* `DEPS`: update to `bpmn-js-element-templates@2.5.1`
* `DEPS`: update to `bpmn-js-properties-panel@5.31.1`
* `DEPS`: update to `camunda-bpmn-js-behaviors@1.9.1`
* `DEPS`: update to `zeebe-bpmn-moddle@1.9.0`
* `FEAT`: support ad-hoc subprocesses in replace menu ([bpmn-js#2276](https://github.com/bpmn-io/bpmn-js/pull/2276))
* `FEAT`: support ad-hoc subprocesses in create/append anything menu ([bpmn-js-create-append-anything#47](https://github.com/bpmn-io/bpmn-js-create-append-anything/pull/47))
* `FEAT`: support _Active elements_ properties for ad-hoc subprocesses …
> Prepare v5.5.0 release

- CHANGELOG.md
- lib/camunda-cloud/features/external-resources/handlers/util/BaseReplaceMenuProvider.js
- test/camunda-cloud/features/external-resources/ResourcesSpec.js
This PR makes sure that we provide group ids for all resources popup menus, including replacement where this was missing.
> fix: use distinct groups for replacement with resource

- CHANGELOG.md
- package-lock.json
- package.json
This PR incorporates camunda-bpmn-js-behaviors@1.10.0. Message ref is not supported for throw events and send task in Camunda 8.
https://github.com/user-attachments/assets/db6fcb5c-3d5e-4b95-b6a3-630abc728638
Related to https://github.com/camunda/camunda-modeler/issues/5003
> deps: update to `camunda-bpmn-js-behaviors@1.10.0

- lib/camunda-cloud/features/popup-menu/CamundaDetailsPopupMenuProvider.js
- package-lock.json
- package.json
- test/camunda-cloud/features/popup-menu/CamundaDetailsPopupMenuProviderSpec.js
Closes https://github.com/camunda/camunda-bpmn-js/issues/401
At the moment the search only supports ranking by alphabetical order. One solution would be to split the search params in something like `search: ['job worker', '1']` & `search: ['job worker', '2']` to give it implicit ordering. But that would result in search results just for numbers (`1`). To manipulate the ranking we can use other chars that are not searchable by normal users (like whitespaces)
have a proper ranking manipulator in diagram js. (not `rank` as this is used to hide stuff before a search is started)
> Rank service task higher than other jobworkers in search
