camunda/camunda-bpmn-js

lib/camunda-cloud/Modeler.js, lib/camunda-platform/Modeler.js, package-lock.json, test/base/ModelerSpec.js, test/camunda-cloud/ModelerSpec.js, test/camunda-platform/ModelerSpec.js
=> fix: resolve moddle descriptors explicitly

lib/camunda-cloud/features/popup-menu/ReplaceOptions.js, lib/camunda-cloud/features/properties-provider/parts/HeadersProps.js, lib/camunda-cloud/features/properties-provider/parts/TaskDefinitionProps.js, lib/camunda-cloud/helper/InputOutputHelper.js, package-lock.json, package.json, test/camunda-cloud/features/popup-menu/ReplaceMenuProviderSpec.js, test/camunda-cloud/features/properties-provider/PropertiesProvider.bpmn, test/camunda-cloud/features/properties-provider/PropertiesProviderSpec.js, test/camunda-cloud/features/properties-provider/parts/InputOutput.bpmn, test/camunda-cloud/features/properties-provider/parts/InputOutputSpec.js, test/fixtures/diagram.bpmn
Adds support for:
* bpmn:SendTask
* bpmn:ScriptTask
* bpmn:BusinessRuleTask
Related to camunda/camunda-modeler#2296
Related to camunda/camunda-modeler#2297
Related to camunda/camunda-modeler#2298
=> Support Zeebe 1.1

lib/camunda-cloud/features/properties-provider/parts/CallActivityProps.js, test/camunda-cloud/features/properties-provider/parts/CallActivitySpec.js
Related to https://github.com/camunda/camunda-modeler/issues/2267
=> fix: do not validate CallActivity#processId expressions

lib/camunda-platform/Modeler.js, lib/camunda-platform/features/modeling/behavior/UpdateCamundaExclusiveBehavior.js, lib/camunda-platform/features/modeling/behavior/index.js, lib/camunda-platform/features/modeling/index.js, test/TestHelper.js, test/camunda-platform/ModelerSpec.js, test/camunda-platform/features/modeling/UpdateCamundaExclusiveBehaviorSpec.js, test/camunda-platform/features/modeling/camunda-exclusive-diagram.bpmn
=> feat(camundaPlatform): add updateCamundaExclusiveBehavior

lib/camunda-platform/features/modeling/behavior/DeleteRetryTimeCycleBehavior.js, lib/camunda-platform/features/modeling/behavior/index.js, test/camunda-platform/ModelerSpec.js, test/camunda-platform/features/modeling/DeleteRetryTimeCycleBehaviorSpec.js, test/camunda-platform/features/modeling/camunda-failed-job-retry-time-cycle-diagram.bpmn
=> 30 add behavior for retry time cycle deletion

lib/camunda-cloud/features/popup-menu/ReplaceOptions.js
Related to https://github.com/camunda/camunda-modeler/issues/2423
=> feat(camunda-cloud): allow to replace Task to ManualTask

CHANGELOG.md
=> Update changelog for v0.10.0

test/base/ModelerSpec.js, test/camunda-cloud/ModelerSpec.js, test/camunda-platform/ModelerSpec.js
This way we are able to validate the resulting XML.
=> test: export on change

CHANGELOG.md, lib/camunda-cloud/features/modeling/behavior/CleanUpBusinessRuleTaskBehavior.js, lib/camunda-cloud/features/modeling/behavior/index.js, package-lock.json, package.json, test/camunda-cloud/features/modeling/CleanUpBusinessRuleTaskBehaviorSpec.js, test/camunda-cloud/features/modeling/process-businessRuleTask.bpmn
closes #65
fixes upstream camunda/camunda-modeler#2524
=> feat(Cloud/Behaviors): add behavior to clean up BusinessRuleTask

CHANGELOG.md, lib/camunda-cloud/features/modeling/behavior/CleanUpAssignmentDefinitionBehavior.js, lib/camunda-cloud/features/modeling/behavior/index.js, test/camunda-cloud/features/modeling/CleanUpAssignmentDefinitionBehaviorSpec.js, test/camunda-cloud/features/modeling/process-user-tasks.bpmn
fix upstream camunda/camunda-modeler#2535
=> feat(cloudBehavior): behavior to clean up empty assignmentDefinitions

package-lock.json, package.json
Cf. https://github.com/bpmn-io/bpmn-js/blob/develop/CHANGELOG.md#883
* Prevent drop on flow from
* Correct resize handles hidden behind element
=> deps: bump to bpmn-js@8.8.3

package-lock.json, package.json
Make double sure we don't release `XXX copy.yyy`.
=> chore: add <clean> script

CHANGELOG.md, package-lock.json, package.json
* `FEAT`: add viewer distributions ([#115](https://github.com/camunda/camunda-bpmn-js/pull/115))
* `CHORE`: import behaviors from camunda-bpmn-js-behaviors ([#116](https://github.com/camunda/camunda-bpmn-js/pull/116))
* `DEPS`: update to `bpmn-js-disable-collapsed-subprocess@0.1.4` ([#112](https://github.com/camunda/camunda-bpmn-js/pull/112))
* `DEPS`: update to `bpmn-js-properties-panel@1.1.0` ([03b659](https://github.com/camunda/camunda-bpmn-js/pull/123/commits/03b659da729364abf97ccc2dba421d83e9f5c48e))
=> chore(CHANGELOG): update to v0.13.0

rollup.config.js, tasks/test-distro.js
Assets weren't getting copied to `dist` and no test verified them being copied. `v0.13.0` was shipped without some of the assets.
=> Fix Distro on Windows

CHANGELOG.md, package-lock.json, package.json, test/camunda-cloud/ModelerSpec.simple.bpmn
https://github.com/camunda/camunda-bpmn-js/compare/v0.13.2...prepare-0-14
=> Prepare 0.14 release

package-lock.json, package.json
Related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/738
=> deps: bump to `zeebe-bpmn-moddle@0.12.2`

lib/camunda-cloud/features/popup-menu/ReplaceOptions.js, test/camunda-cloud/features/popup-menu/ReplaceMenuProviderSpec.js, test/fixtures/diagram.bpmn
* adds replacement option
---
Related to https://github.com/camunda/camunda-modeler/issues/3083
=> feat(cloud): add inclusive gateway replacement option

lib/camunda-cloud/features/popup-menu/ReplaceOptions.js, test/camunda-cloud/features/popup-menu/ReplaceMenuProviderSpec.js
related to https://github.com/camunda/camunda-modeler/issues/3149
=> feat(cloud): support terminate end event

CHANGELOG.md, package-lock.json, package.json
* allow major updates in accordance with https://github.com/camunda/linting/commit/c2962f9682ea1b409d4911f3c5bbb2c04f3541e5
---
Related to https://github.com/camunda/camunda-modeler/issues/3246
=> deps: update bpmn-js-properties-panel dependency

.github/workflows/CI.yml
Conditions don't need to be updated anymore when os version changes.
---
Follow-up for https://github.com/camunda/camunda-bpmn-js/pull/198
=> ci: check conditions based on os type

CHANGELOG.md, package-lock.json, package.json
* update to `bpmn-js-properties-panel@1.11.1`
* update changelog
---
Related to https://github.com/camunda/camunda-modeler/issues/3151
=> Update Properties Panel Dependency

lib/camunda-cloud/Modeler.js, lib/camunda-platform/Modeler.js, package-lock.json, package.json, rollup.config.js, tasks/test-distro.js, test/camunda-cloud/ModelerSpec.js, test/camunda-platform/ModelerSpec.js
Adds the color picker extension to platform and cloud diagrams:
Closes #217
Closes https://github.com/camunda/modeler-design/issues/101
=> Integrate color picker

lib/camunda-cloud/features/replace/ElementTemplatesReplaceProvider.js, package.json, test/camunda-cloud/ElementTemplatesReplaceProviderSpec.js, test/camunda-cloud/ModelerSpec.js
Closes #220 
Following https://github.com/camunda/camunda-bpmn-js/issues/220#issuecomment-1350950639, I removed the connectors extension from the base test case and added some integration tests for it.
=> Fix label for element template replace menu entries

CHANGELOG.md, lib/camunda-cloud/Modeler.js, lib/camunda-platform/Modeler.js, package-lock.json, package.json, test/camunda-platform/ModelerSpec.js
This PR integrates https://github.com/bpmn-io/variable-resolver into camunda-bpmn-js and allows us (and the users) to register variable providers through additional modules/modeler plug-ins
=> feat: add variable resolver

.gitignore, CHANGELOG.md, lib/base/Modeler.js, lib/camunda-cloud/Modeler.js, lib/camunda-cloud/Modeler.spec.ts, lib/camunda-cloud/NavigatedViewer.js, lib/camunda-cloud/NavigatedViewer.spec.ts, lib/camunda-cloud/Viewer.js, lib/camunda-cloud/Viewer.spec.ts, lib/camunda-cloud/features/rules/BpmnRules.js, lib/camunda-cloud/util/commonModules.js, lib/camunda-platform/Modeler.js, lib/camunda-platform/Modeler.spec.ts, lib/camunda-platform/NavigatedViewer.js, lib/camunda-platform/NavigatedViewer.spec.ts, lib/camunda-platform/Viewer.js, lib/camunda-platform/Viewer.spec.ts, lib/camunda-platform/util/commonModules.js, lib/util/ExtensionElementsUtil.js, package-lock.json, package.json, tsconfig.json
Requires https://github.com/bpmn-io/bpmn-js/pull/1899.
=> Add Type Declarations

CHANGELOG.md, package-lock.json, package.json
related to https://github.com/camunda/camunda-modeler/issues/3599 and https://github.com/camunda/camunda-modeler/issues/3510
=> deps: update to @bpmn-io/variable-resolver@1.1.0

package-lock.json, package.json, test/camunda-cloud/ModelerSpec.js
=> chore: remove `bpmn-js-connectors-extension` dependency

CHANGELOG.md, lib/camunda-platform/Modeler.js, package-lock.json, package.json
=> feat: remove template when replacing with stock BPMN

CHANGELOG.md, package-lock.json, package.json, rollup.config.mjs, test/base/ModelerSpec.js, test/camunda-cloud/ModelerSpec.js, test/camunda-platform/ModelerSpec.js
related to https://github.com/camunda/camunda-modeler/issues/3782
=> `FIX`: remove output group from error end events 

CHANGELOG.md, package-lock.json, package.json
=> deps: update to bpmn-js-element-templates@1.4.0

CHANGELOG.md, lib/camunda-cloud/Modeler.js, package-lock.json, package.json, rollup.config.mjs
related to https://github.com/camunda/camunda-modeler/issues/3728
related to https://github.com/camunda/camunda-modeler/issues/3780
=> Update variable providers

.github/workflows/CI.yml
Related to https://github.com/bpmn-io/internal-docs/issues/818
=> chore(CI): target node v20

CHANGELOG.md, package-lock.json, package.json, test/camunda-cloud/ModelerSpec.js
* `DEPS`: update to `camunda-bpmn-js-behaviors@1.2.0`
* `FEAT`: ensure that only one type of form is set at a time ([bpmn-io/bpmn-js-properties-panel](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/949))
* `FEAT`: remove `zeebe:subscription` when no properties are left ([bpmn-io/bpmn-js-element-templates](https://github.com/bpmn-io/bpmn-js-element-templates/issues/21))
=> deps: update to `camunda-bpmn-js-behaviors@1.2.1`

CHANGELOG.md, package-lock.json, package.json
fix: display multi-instance configuration in properties panel
=> deps: update to `bpmn-js-element-templates@1.6.1`

package-lock.json, package.json
I think it was installed to production deps by accident.
=> deps: move typescript to devDependencies

package-lock.json
=> deps: update to lezer-feel@1.2.6

CHANGELOG.md, package-lock.json, package.json
related to https://github.com/camunda/camunda-modeler/issues/4139
This will fix the web modeler issue https://github.com/camunda/web-modeler/issues/8469
=> deps: update @bpmn-io/variable-resolver to v1.2.2

CHANGELOG.md, package-lock.json, package.json
related to https://github.com/camunda/camunda-modeler/issues/4220
=> deps: update to `@camunda/example-data-properties-provider@1.2.1`

.github/PULL_REQUEST_TEMPLATE.md
Related to https://github.com/bpmn-io/.github/pull/7
=> chore(.github): add PULL_REQUEST_TEMPLATE

CHANGELOG.md, package-lock.json, package.json
* integrates https://github.com/camunda/camunda-bpmn-js-behaviors/pull/81
=> deps: update camunda-bpmn-js-behaviors to v1.6.1

CHANGELOG.md, package-lock.json
Related to https://github.com/camunda/camunda-modeler/issues/4500
=> deps: bump @bpmn-io/feel-editor

CHANGELOG.md, lib/camunda-cloud/Modeler.js, package-lock.json, package.json, test/camunda-cloud/ModelerSpec.js
* configures default FEEL popup links
* adds new link to FEEL copilot 
Depends on https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1083
Related to https://github.com/camunda/product-hub/issues/2070#issuecomment-2449888911
=> Configure FEEL Popup Links

CHANGELOG.md, package-lock.json, package.json
This PR bumps up dependencies related to task listeners implementation.
related to https://github.com/camunda/camunda-modeler/issues/4590
=> Support task listeners

CHANGELOG.md, package-lock.json, package.json
Integrates https://github.com/camunda/camunda-bpmn-js-behaviors/pull/85.
Related to https://github.com/camunda/camunda-modeler/issues/4658
=> deps: update to camunda-bpmn-js-behaviors@1.7.2

CHANGELOG.md, lib/camunda-cloud/Modeler.js, lib/camunda-cloud/features/popup-menu/CamundaDetailsPopupMenuProvider.js, lib/camunda-cloud/features/popup-menu/index.js, package-lock.json, package.json, test/camunda-cloud/features/popup-menu/CamundaDetailsPopupMenuProvider.bpmn, test/camunda-cloud/features/popup-menu/CamundaDetailsPopupMenuProviderSpec.js
This tags create/append/replace options with Camunda context, so we support our users better in implementing Camunda:
Related to Related to https://github.com/camunda/camunda-modeler/issues/4802
=> Tag create/append/replace options with Camunda context

CHANGELOG.md, package-lock.json, package.json
=> Bumb-bpmn-dep-18-3-2

CHANGELOG.md, package-lock.json, package.json
* update deps: `FIX`: copy error, escalation, message and signal references when copying elements ([bpmn-io/bpmn-js#2301](https://github.com/bpmn-io/bpmn-js/pull/2301))
=> deps: update to bpmn-js@18.6.1
